- name: Ensure Nginx is installed
  apt:
    pkg: nginx
    state: present
    default_release: latest
  register: nginx_installed

- name: Install Nginx if not installed
  when: not nginx_installed.stat.exists
  apt:
    name: nginx
    state: latest
  notify: Reload Nginx

- name: Ensure openssl is installed
  apt:
    pkg: openssl
    state: latest
  when: nginx_ssl
  tags:
    - system
    - install

- name: Ensure all folders exists
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    mode: u=rwx,g=rx,o=rx # 755
  with_items:
    - modules-available
    - modules-enabled
    - sites-available
    - sites-enabled
    - conf.d

- name: Ensure configuration is set
  template:
    src: "{{ item.src }}"
    dest: /etc/nginx/{{ item.path }}
    mode: u=rw,g=r,o=r # 0644
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"
  notify:
    - reload nginx
    - restart nginx

- name: Ensure cache dir exists
  file:
    path: "{{ nginx_cache_dir }}"
    state: directory
    owner: www-data
    mode: u=rwx,g=,o= # 700 (only the user can read, write and execute)

- name: Stop Nginx
  service:
    name: nginx
    state: stopped

- name: Get Nginx version
  command: /usr/sbin/nginx -v
  register: nginx_version

- name: Copy previous Nginx binary
  copy:
    src: /usr/sbin/nginx
    dest: /usr/sbin/{{ nginx_version }}_{{ ansible_date_time.iso8601 }}.bak
  when: nginx_installed.stat.exists

- name: Download latest homemade build of Nginx
  get_url:
    url: https://github.com/bolinocroustibat/nginx-http3/releases/latest/download/nginx
    dest: /usr/sbin/nginx
    mode: u=rwx,g=rx,o=rx
  notify:
    - restart nginx

- name: Ensure service is started and enabled at boot
  service:
    name: nginx
    state: started
    enabled: true

- name: Ensure www-data user exists
  user:
    name: www-data
    state: present
    system: true

- name: Ensure user www-data is in the www-data group
  user:
    name: www-data
    groups: www-data
    append: yes
