- name: Backup existing .bashrc if it exists
  copy:
    src: "{{ user_home }}/.bashrc"
    dest: "{{ user_home }}/.bashrc_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Write .bashrc
  template:
    src: .bashrc.j2
    dest: "{{ user_home }}/.bashrc"
    mode: "u=rw,go=r"
