---

- name: Install NVM
  homebrew:
    name: nvm
    state: latest
  when: ansible_os_family == "Darwin"


- name: Install/select node version with NVM
  ansible.builtin.command: nvm install {{ node_version }}
  become: true
  when: ansible_os_family == "Darwin"
