- name: Install NVM
  homebrew:
    name: nvm
    state: latest
  when: ansible_os_family == "Darwin"


- name: Install/select node version with NVM
  command: nvm install {{ node_version }}
  when: ansible_os_family == "Darwin"
