[project]
name = "dotfiles"
version = "0.1.0"
description = "Ansible playbooks for setting up local development and remote machines"
authors = [{ name = "Adrien Carpentier", email = "me@adriencarpentier.com" }]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
dependencies = [
    "ansible>=10.4.0",
]

[tool.ruff]
line-length = 100
lint = { extend-select = ["I"] }

[tool.uv]
dev-dependencies = [
    "ansible-lint>=24.9.2",
    "ruff>=0.6.7",
]
environments = ["platform_system != 'Windows'"]
