- name: Install direnv with homebrew
  homebrew:
    name: direnv
    state: latest
  when: ansible_os_family == "Darwin"

- name: Install direnv with apt
  apt:
    name: direnv
    state: latest
  when: ansible_os_family == "Debian"

- name: Backup existing config file if it exists
  copy:
    remote_src: true
    src: "{{ user_home }}/.config/direnv/direnv.toml"
    dest: "{{ user_home }}/.config/direnv/direnv.toml_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Configure direnv for taking .env files into account
  template:
    src: direnv.toml.j2
    dest: "{{ user_home }}/.config/direnv/direnv.toml"
    mode: u=rw,g=r,o=r
