- name: Check if Oh-My-ZSH is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: oh_my_zsh__installed

- name: Install Oh-My-ZSH
  when: not oh_my_zsh__installed.stat.exists
  block:
    - name: Create temporary file
      tempfile:
        state: file
      register: oh_my_zsh__install_script

    - name: Download Oh-My-ZSH installation script
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
        mode: u=rwx,g=rx,o=rx

    - name: Install Oh-My-ZSH installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
      changed_when: ohmyzsh_result.find('The $ZSH folder already exists') == -1

    - name: Remove the temporary file
      file::
        path: /tmp/install_ohmyzsh.sh
        state: absent
      when: oh_my_zsh__install_script.path is defined

    - name: Clone zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ user_home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
        version: master
        force: true
      when: user.oh_my_zsh__install_zsh_autosuggestions | default(oh_my_zsh__install_zsh_autosuggestions)

    - name: Clone zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: "{{ user_home }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
        version: master
        force: true
      when: user.oh_my_zsh__install_zsh_syntax_highlighting | default(oh_my_zsh__install_zsh_syntax_highlighting)

    - name: Install custom theme from template
      template:
        src: bolino.zsh-theme.j2
        dest: "{{ user_home }}/.oh-my-zsh/custom/themes/bolino.zsh-theme"
        mode: u=rw,g=r,o=r

- name: Backup existing .zshrc if it exists
  copy:
    src: "{{ user_home }}/.zshrc"
    dest: "{{ user_home }}/.zshrc_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Write .zshrc
  template:
    src: .zshrc.j2
    dest: "{{ user_home }}/.zshrc"
    mode: "u=rw,go=r"
