- name: Update global pip
  command: "python3 -m pip install --upgrade pip"
  register: pip_update_result
  changed_when: "'Successfully installed pip-' in pip_update_result.stdout"
  failed_when: "'error' in pip_update_result.stderr"
