---

- name: Create ~/.ssh directory in user home
  file:
    path: "{{ user_home_path }}/.ssh"
    state: directory
    owner: {{ ansible_user }}
    group: {{ ansible_user }}
    mode: 0700

- name: Download SSH public key
  uri:
    url: http://adriencarpentier.com/id_ed25519.pub
    dest: "{{ user_home_path }}/.ssh/id_ed25519.pub"
    mode: 0600
    owner: {{ ansible_user }}
    group: {{ ansible_user }}

- name: Add SSH public key to authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '{{ user_home_path }}/.ssh/id_ed25519.pub') }}"
    state: present
