---

- name: Create ~/.ssh directory in user home
  ansible.builtin.fil:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: Download SSH public key
  ansible.builtin.uri:
    url: http://adriencarpentier.com/id_ed25519.pub
    dest: "{{ user_home }}/.ssh/id_ed25519.pub"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Add SSH public key to authorized_keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '{{ user_home }}/.ssh/id_ed25519.pub') }}"
    state: present
