- name: Check if ZSH is installed
  block:
    - name: Check if ZSH is installed with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zsh
        state: present
      register: zsh_installed

    - name: Check if ZSH is installed with apt
      when: ansible_os_family == "Debian"
      apt:
        name: zsh
        state: present
        update_cache: true
      become: true
      register: zsh_installed

- name: Install ZSH
  when: not zsh_installed.changed
  block:
    - name: Install ZSH with homebrew
      when: ansible_os_family == "Darwin"
      homebrew:
        name: zsh
        state: latest

    - name: Install ZSH with apt
      when: ansible_os_family == "Debian"
      apt:
        name: zsh
        state: latest
        update_cache: true
      become: true

- name: Change current user shell to ZSH
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
