- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

- name: reload nginx config
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true
