- name: Install ufw
  apt:
    name: ufw
    state: latest
    update_cache: true

- name: Allow SSH
  command: ufw allow ssh

- name: Allow Nginx HTTP
  command: ufw allow 'Nginx HTTP'

- name: Allow Nginx HTTPS
  command: ufw allow 'Nginx HTTPS'

- name: Reload ufw
  command: ufw reload

- name: Enable ufw
  command: ufw enable
