- name: Install UFW
  apt:
    name: ufw
    state: latest
    update_cache: true

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Allow SSH
  community.general.ufw:
    rule: allow
    name: ssh

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    name: http

- name: Enable UFW
  community.general.ufw:
    state: enabled
