- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  when: user.install_git | default(install_git)

- name: Configure git
  blocks:
    - name: Set Git user name
      when: user.git_user_name is defined
      command: git config --global user.name "{{ user.git_user_name }}"
      changed_when: false

    - name: Set Git user email
      when: user.git_user_email is defined
      command: git config --global user.email "{{ user.git_user_email }}"
      changed_when: false

    - name: Set Git user signing key
      command: git config --global user.signingkey "{{ user_home }}/.ssh/id_ed25519.pub"

    - name: Set Git user GPG key
      command: git config --global user.gpgsign true

    - name: Set Git user editor
      command: git config --global core.editor micro
      changed_when: false
