---

- name: Download uv installation script
  uri:
    url: 'https://astral.sh/uv/install.sh'
    method: GET
    follow_redirects: safe
    # force: yes
    dest: "/tmp/uv_install.sh"
    mode: "0700"

- name: Define uv install dir path
  set_fact:
    uv_install_dir: "{{ '/usr/local/bin/uv' if uv_multi_users else '{{ user_home }}/.cargo' }}"

- name: Set UV_INSTALL_DIR env var for multi-users uv installation
  set_fact:
    UV_INSTALL_DIR: "{{ uv_install_dir }}"
  when: uv_multi_users

- name: Execute uv installation script
  command: "sh /tmp/uv_install.sh"
  register: uv_result
  failed_when: "'FAILED' in uv_result.stderr"

- name: Remove the temporary installation script
  file::
    path: "/tmp/uv_install.sh"
    state: absent

- name: Install Python 3.12 with uv
  command: "{{ uv_install_dir }}/bin/uv python install 3.12"
