- name: Update uv
  command: "{{ uv_install_dir }}/bin/uv self update"
  register: uv_result
  changed_when: "'on the latest version of uv' not in uv_result.stderr"
  failed_when: "'Err' in uv_result.msg"
