- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: true

- name: Add jail.local file
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  notify: restart fail2ban

- name: Add jail.d files
  copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  with_fileglob:
    - files/jail.d/*
  notify: restart fail2ban

- name: Start fail2ban service
  service:
    name: fail2ban
    state: started

- name: Enable fail2ban service
  service:
    name: fail2ban
    enabled: true
