---

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  become: true

- name: Add jail.local file
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  when: ansible_os_family == 'Debian'

- name: Add jail.d files
  copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/jail.d/*
  notify: restart fail2ban
  when: ansible_os_family == 'Debian'

- name: Start fail2ban service
  service:
    name: fail2ban
    state: started
  become: true

- name: Enable fail2ban service
  service:
    name: fail2ban
    enabled: true
  become: true
