- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: true

- name: Backup existing jail.local file if it exists
  copy:
    src: "/etc/fail2ban/jail.local"
    dest: "/etc/fail2ban/jail.local_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Add jail.local file
  template:
    src: jail.local.j2
    dest: "/etc/fail2ban/jail.local"
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  notify: restart fail2ban

- name: Backup existing jail.d/* files if they exist
  copy:
    src: "/etc/fail2ban/jail.d/*"
    dest: "/etc/fail2ban/jail.d/*_{{ ansible_date_time.iso8601 }}.bak"
    mode: preserve # Preserve the file permissions of the original file

- name: Add jail.d/* files
  template:
    src: "{{ item }}"
    dest: "/etc/fail2ban/jail.d/{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r # 644
  with_fileglob:
    - ../templates/jail.d/*
  notify: restart fail2ban

- name: Enable fail2ban service
  service:
    name: fail2ban
    enabled: true
