- name: Install Micro text editor with homebrew
  when: ansible_os_family == "Darwin"
  homebrew:
    name: micro
    state: latest

- name: Install Micro text editor with apt
  when: ansible_os_family == "Debian"
  apt:
    name: micro
    state: latest
    update_cache: true

- name: Backup existing config file if it exists
  copy:
    src: "{{ user_home }}/.config/micro/settings.json"
    dest: "{{ user_home }}/.config/micro/settings.json.backup_{{ ansible_date_time.iso8601 }}"
    mode: preserve # Preserve the file permissions of the original file

- name: Copy config file
  template:
    src: settings.json.j2
    dest: "{{ user_home }}/.config/micro/settings.json"
    mode: u=rw,g=r,o=r
