- name: Install Micro text editor with homebrew
  homebrew:
    name: micro
    state: latest
  when: ansible_os_family == "Darwin"

- name: Install Micro text editor with apt
  apt:
    name: micro
    state: latest
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Backup existing config file if it exists
  copy:
    src: "{{ user_home }}/.config/micro/settings.json"
    dest: "{{ user_home }}/.config/micro/settings.json.backup_{{ ansible_date_time.iso8601 }}"

- name: Copy config file
  template:
    src: settings.json.j2
    dest: "{{ user_home }}/.config/micro/settings.json"
