- name: Update apt and upgrade packages
  hosts: remote
  tasks:
    - include_role:
        name: apt
        tasks_from: upgrade
    - include_role:
        name: apt
        tasks_from: install_sources

- name: Configure .bashrc
  hosts: remote
  tasks:
    - include_role:
        name: bash
        tasks_from: main

- name: Install zsh
  hosts: remote
  tasks:
    - include_role:
        name: zsh
        tasks_from: main

- name: Install and configure oh-my-zsh
  hosts: remote
  tasks:
    - include_role:
        name: oh_my_zsh
        tasks_from: install

- name: Add the GitHub Actions user
  hosts: local
  tasks:
    - include_role:
        name: github_actions
        tasks_from: main

- name: Install and configure Micro
  hosts: remote
  tasks:
    - include_role:
        name: micro
        tasks_from: main

- name: Install and configure fail2ban
  hosts: remote
  tasks:
    - include_role:
        name: fail2ban
        tasks_from: main

- name: Install and configure ufw
  hosts: remote
  tasks:
    - include_role:
        name: ufw
        tasks_from: main

- name: Install and configure Nginx
  hosts: remote
  tasks:
    - include_role:
        name: nginx
        tasks_from: main

- name: Install and configure uv
  hosts: remote
  tasks:
    - include_role:
        name: uv
        tasks_from: install
