---

- name: Install and update Homebrew
  hosts: local
  tasks:
    - include_role:
        name: homebrew
        tasks_from: [install, update]

- name: Updating Ruby gems
  hosts: local
  tasks:
    - name: Updating Ruby gems
      command: gem update --system
      become: false

- name: Install zsh and oh-my-zsh
  hosts: local
  tasks:
    - include_role:
        name: zsh
        tasks_from: main

- name: Install direnv
  hosts: local
  tasks:
    - include_role:
        name: direnv
        tasks_from: main

- name: Install Micro
  hosts: local
  tasks:
    - include_role:
        name: micro
        tasks_from: main

- name: Install uv
  hosts: local
  tasks:
    - include_role:
        name: uv
        tasks_from: main

- name: Install NVM
  hosts: local
  tasks:
    - include_role:
        name: nvm
        tasks_from: main

- name: Install pnpm
  hosts: local
  tasks:
    - include_role:
        name: pnpm
        tasks_from: main
